image:
  - Visual Studio 2017
  - Ubuntu

version: 2.6.4.{build}

pull_requests:
  do_not_increment_build_number: true

configuration: Release

platform:
- x64

build:
  project: nx.sln
  verbosity: minimal

for:
-
  matrix:
    only:
      - image: Ubuntu

  build_script:
  - travis/linux.install.sh
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - make

before_deploy:
 - ps: .\platform\win32\win.package.ps1

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: ''
    auth_token:
      secure: UNAaCG+KMRMqZqVEHpSgXTXZOJlqEQ/7nySQ6U/LutHjXnuqVNpYDxoqIW1hufI+
    artifact: /NXEngine-.*\.zip/
    draft: true
    force_update: true
    prerelease: false
    on:
      appveyor_repo_tag: true
